name: Add ghommit to /usr/local/bin
description: Add ghommit to /usr/local/bin
inputs:
  access_token:
    description: 'A personal access token (PAT) or installation access token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add ghommit to /usr/local/bin
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        GITHUB_OWNER: gemini-oss
        GITHUB_REPO: ghommit
        TAG: v0.0.8
        LINUX_AARCH64_FILENAME: ghommit-linux-aarch64
        LINUX_AARCH64_HASH: 64bbf306d4d1490f647fec6bf16af181e33c860b6e3e9c789f694efac532ef10
        LINUX_X86_64_FILENAME: ghommit-linux-x86_64
        LINUX_X86_64_HASH: 6f1f0e9385d972a1343d530aa17d92d1b8ecdde0f95a76fb6641d68cfc7daafc
      shell: bash
      run: |
        set -euo pipefail

        ARCHITECTURE=$(uname -m)

        case "${ARCHITECTURE}" in
          arm64|aarch64)
            ASSET_NAME="${LINUX_AARCH64_FILENAME}"
            EXPECTED_HASH="${LINUX_AARCH64_HASH}"
            ;;
          amd64|x86_64)
            ASSET_NAME="${LINUX_X86_64_FILENAME}"
            EXPECTED_HASH="${LINUX_X86_64_HASH}"
            ;;
          *)
            echo "Unsupported architecture: ${ARCHITECTURE}" >&2
            exit 1
            ;;
        esac

        URL="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/${TAG}/${ASSET_NAME}"

        curl -sSL \
          -H "Authorization: Bearer ${ACCESS_TOKEN}" \
          -o ghommit \
          "${URL}"

        echo "${EXPECTED_HASH}  ghommit" | sha256sum -c -

        chmod +x ghommit
        sudo mv ghommit /usr/local/bin
